version: '3'

services:
    build-hentai:
        image: hentaios/docker-buildcakes:latest
        container_name: hentai-buildsystem
        hostname: NekoInfra
        stdin_open: true
        tty: true
        volumes:
            - ~/hentai:/repo
            - ~/hentaicache:/tmp/ccache
