name: Build and Push Docker Image
on: [push]

jobs:
  BuildPush:
    name: Buildpush
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: H
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
            github-token: ${{ secrets.PANCAKE }}
            image-name: hentai-buildcakes
            image-tag: latest
